
default_language_version:
    python: python3
files: |
    (?x)^(
        (
            .github|
            chrobalt|
            ui/ozone/platform/starboard |
            docker-compose.yml |
            .pre-commit-config.yaml
        )
    )

repos:
-   repo: https://cobalt.googlesource.com/pre-commit-hooks
    rev: e1668fe86af3810fbca72b8653fe478e66a0afdc  # v3.2.0
    hooks:
    -   id: check-case-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending

-   repo: local
    hooks:
    -   id: yapf
        name: yapf
        description: Run yapf (the python formatter) in-place on changed files.
        entry: yapf
        language: python
        additional_dependencies:
          - "yapf"
        types: [python]
        args: [-i, -vv]
    -   id: pylint
        name: pylint
        description: Run Pylint in-place on changed files.
        entry: pylint
        language: python
        types: [python]
        additional_dependencies:
          - "pylint"
